repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
      - id: isort
        args: ["--profile", "black"]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.256'
  hooks:
    - id: ruff